name: Flask CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t flaskapp:latest .

    - name: Run container test
      run: docker run -d -p 8000:8000 flaskapp:latest

