name: Build and Push Docker Compose App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push app image
        run: |
          docker compose build app
          docker tag flaskapp_app:latest ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest
